---
title: "NN_regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(keras)
library(tensorflow)
library(tfdatasets)
library(dplyr)
```

```{r}
boston_housing <- dataset_boston_housing()

#c(train_data, train_labels) %<-% boston_housing$train
#c(test_data, test_labels) %<-% boston_housing$test

train_data <- as.matrix(x_train)
train_labels <- as.array(y_train[,1])
test_data <- as.matrix(x_test)
test_labels <- as.array(y_test[,1])

```

```{r}
column_names <- c('CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 
                  'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT')

column_names <- colnames(x_train)

train_df <- train_data %>% 
  as_tibble(.name_repair = "minimal") %>% 
  setNames(column_names) %>% 
  mutate(label = train_labels)

test_df <- test_data %>% 
  as_tibble(.name_repair = "minimal") %>% 
  setNames(column_names) %>% 
  mutate(label = test_labels)
```

```{r}
spec <- feature_spec(train_df, label ~ . ) %>% 
  step_numeric_column(all_numeric(), normalizer_fn = scaler_standard()) %>% 
  fit()

spec
```

```{r}
layer <- layer_dense_features(
  feature_columns = dense_features(spec), 
  dtype = tf$float32
)
layer(train_df)
```

```{r}

#sigmoid = function(x) 1 / (1 + exp(-x))

input <- layer_input_from_dataset(train_df %>% select(-label))

output <- input %>% 
  layer_dense_features(dense_features(spec)) %>% 
  layer_dense(units = 128, activation = "sigmoid",input_shape=c(18)) %>%
  layer_dense(units = 64, activation = "sigmoid") %>%
  layer_dense(units = 32, activation = "sigmoid") %>%
  layer_dense(units = 16, activation = "sigmoid") %>%
  layer_dense(units = 1) #1 node = continuous output

model <- keras_model(input, output)

summary(model)
```

```{r}
model %>% 
  compile(
    loss = "mse",
    optimizer = optimizer_rmsprop(),
    metrics = list("mean_absolute_error")
  )
```

```{r}
build_model <- function() {
  input <- layer_input_from_dataset(train_df %>% select(-label))
  
  output <- input %>% 
    layer_dense_features(dense_features(spec)) %>% 
    layer_dense(units = 64, activation = "relu") %>%
    layer_dense(units = 64, activation = "relu") %>%
    layer_dense(units = 1) 
  
  model <- keras_model(input, output)
  
  model %>% 
    compile(
      loss = "mae",
      optimizer = optimizer_rmsprop(),
      metrics = list("mean_absolute_error")
    )
  
  model
}
```

```{r}

#model <- build_model()

history <- model %>% fit(
  x = train_df %>% select(-label),
  y = train_df$label,
  epochs = 30,
  validation_split = 0.2
)
```

```{r}
c(loss, mae) %<-% (model %>% evaluate(test_df %>% select(-label), test_df$label, verbose = 0))
mae
```

```{r}
# compute the accuracy by demographic variables
# report tips
# start with outline
# skeleton document with tables and figures
# then fill in report with text
test_predictions <- model %>% predict(test_df %>% select(-label))
test_predictions[ , 1]
```

```{r}
df_gender_bag <- data.frame(test_df$RIAGENDR,test_df$RIDAGEYR,test_df$label,test_predictions[,1])

df_men <- df_gender_bag[df_gender_bag$test_df.RIAGENDR == 1,]
df_women <- df_gender_bag[df_gender_bag$test_df.RIAGENDR == 2,]

error_men <- mean(sqrt((df_men$test_predictions...1. - df_men$test_df.label)^2))
error_women <- mean(sqrt((df_women$test_predictions...1. - df_women$test_df.label)^2))

error_men / (error_women + error_men)
error_men
error_women
```
