---
title: "R Notebook"
output: html_notebook
---

```{r}
#Loads in 205 variables with at least 10,000 data entries
load('/Users/colinbrant/Downloads/capstone-main/selected_Winsorized_df.Rdata')
load('/Users/colinbrant/Downloads/capstone-main/NHANES_Clean.RData')
df <- select
df$CBD121[df$CBD121 == 777777] <- NA
df$WHD110[df$WHD110 == 9999 | df$WHD110 == 7777] <- NA
head(df)
```

```{r}
#All quantative variables available in the select dataset
quant <- c("LBDHDD", "LBDHDDSI", "LBXTR","LBDTRSI" , "LBDLDL"  , "LBDLDLSI", "LBXTC"   , "LBDTCSI" , "LBXGLU"  , "LBDGLUSI" ,"CBD121"  , "CBD131"  ,"DBD900"  , "DBD905"  , "DBD910"  , "PAQ625"  , "PAD630"  , "PAQ670"  , "PAD675"  , "PAD680"  , "WHD010"  , "WHD020"  , "WHD050"  , "WHD110", "WHD120" ,  "WHD130"   ,"WHD140" ,  "WHQ150" ,  "BMXWT"  ,  "BMXHT"  ,  "BMXBMI" ,  "BMXLEG" ,  "BMXARML"  ,"BMXARMC",   "BPD035"  ,"INDFMPIR", "WTINT2YR", "WTMEC2YR")
quant_df <- select[, quant]
quant_df$Hypertension <- select$BPQ020
quant_df$Waist_Circumference <- select$BMXWAIST
head(quant_df)
```


Change coding of Hypertension Response
```{r}
quant_df$Hypertension <- as.integer(quant_df$Hypertension)
quant_df$Hypertension[quant_df$Hypertension == 1] <- 1
quant_df$Hypertension[quant_df$Hypertension == 2] <- 0
quant_df$Hypertension <- as.factor(quant_df$Hypertension)
```


To include gender (RIAGENDR) and age in years (RIDAGEYR)
```{r}
quant_df$Age <- select$RIDAGEYR
quant_df$Gender <- select$RIAGENDR
quant_df$Total_Cholesterol <- select$LBDTCSI
quant_df$Height <- select$BMXHT
quant_df$BMI <- select$BMXBMI
quant_df$LDL_Cholesterol <- select$LBDLDL
Hypertension <- quant_df$Hypertension
vars <- c('Total_Cholesterol','CBD121','DBD910','PAD680','WHD020','WHD110','WHD130','Height','BMI', 'BMXLEG', 'BMXARML', 'BMXARMC','Waist_Circumference','Age','Gender', 'Hypertension', 'LDL_Cholesterol')
```

Create new df for variables to used in final report summary
```{r}
quant_df2 <- quant_df[vars]
sum <- c('Total_Cholesterol','Waist_Circumference','Height','Age','Gender','BMI','Hypertension','LDL_Cholesterol')
sub_tab <- quant_df2[sum]
library(tableone)
```

```{r}
tab1 <- CreateTableOne(data=sub_tab)
summary(tab1)
```
```{r}
summary(sub_tab)
```

